/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    alias(libs.plugins.palantir.git.version)
    alias(libs.plugins.gradleup.shadow)
}

repositories {
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    compileOnly("com.velocitypowered:velocity-api:3.4.0-SNAPSHOT")
    annotationProcessor("com.velocitypowered:velocity-api:3.4.0-SNAPSHOT")
}

val gitVersion: groovy.lang.Closure<String> by extra
version = gitVersion() // last tag + commit distance + short hash

tasks.shadowJar {
    exclude("org/slf4j/**")
    archiveClassifier = ""
}

tasks.assemble {
    dependsOn(tasks.shadowJar) // Ensure that the shadowJar task runs before the build task
}

tasks.jar {
    enabled = false // Disable the default jar task since we are using shadowJar
}