/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "LangLibs"
include(":LangLibs-API")
include(":LangLibs-Paper")
include(":LangUI-Paper")
project(":LangLibs-API").projectDir = file("langlibs-api")
project(":LangLibs-Paper").projectDir = file("langlibs-paper")
project(":LangUI-Paper").projectDir = file("langui-paper")
