# Where player language preferences are stored / fetched from.
# Options: mysql | velocity
data-source: mysql

database:
  url: ""
  name: ""
  username: ""
  password: ""

# NOTE: Do not change
version: 1