/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":LangLibs-API"))
    compileOnly(libs.io.papermc.paper.paper.api)
}
