/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    `maven-publish`
    alias(libs.plugins.gradleup.shadow)
}

version = "1.5.1"

dependencies {
    api(libs.org.mariadb.jdbc.mariadb.java.client)
    api(libs.com.zaxxer.hikaricp)
    api(libs.org.spongepowered.configurate.yaml)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.commons.io.commons.io)
}

val alpsMavenUser: String? = project.findProperty("alpsMavenUser") as String?
val alpsMavenPassword: String? = project.findProperty("alpsMavenPassword") as String?

publishing {
    publications {
        create<MavenPublication>("shadow") {
            from(components["shadow"])
        }
    }
    repositories {
        maven {
            credentials {
                username = alpsMavenUser
                password = alpsMavenPassword
            }
            url = uri("https://mvn.alps-bte.com/repository/alps-bte/")
        }
    }
}

tasks.shadowJar {
    exclude("org/slf4j/**")
    exclude("org/jetbrains/annotations/**")
    archiveClassifier = ""
}

tasks.assemble {
    dependsOn(tasks.shadowJar) // Ensure that the shadowJar task runs before the build task
}

tasks.jar {
    enabled = false // Disable the default jar task since we are using shadowJar
}