/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.alpsbte.canvas)
    api(libs.com.alpsbte.alpslib.alpslib.utils)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(project(":LangLibs-API"))
}