name: Build & Upload LangLibs-Paper

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  path:
    - 'langlibs-paper/**'
    - '.github/workflows/build-langlibs-paper.yml'
    - 'gradle/**'
    - 'buildSrc/**'
    - 'langlibs-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :LangLibs-Paper:build

      - uses: actions/upload-artifact@v4
        with:
          name: Staging-Build
          path: langlibs-paper/build/libs
          compression-level: '9'
