name: Build and Deploy LangLibs-API

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'langlibs-api/build.gradle.kts'
    # - 'langlibs-api/**'
    # - '.github/workflows/deploy-api.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew :LangLibs-API:build

    - name: Deploy LangLibs-API to Maven repository
      run: ./gradlew :LangLibs-API:publish
      env:
        ORG_GRADLE_PROJECT_alpsMavenUser: ${{ secrets.MAVEN_USERNAME }}
        ORG_GRADLE_PROJECT_alpsMavenPassword: ${{ secrets.MAVEN_PASSWORD }}